config/routes.rb
Rails.application.routes.draw do
  

  resources :investments do

  resources :withdrawals
  
  end

  resources :topics, only: [:index, :show]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  get 'rent', to: 'listings#rent'
  get 'buy', to: 'listings#buy'
  get 'property', to: 'listings#property'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'agents/:id', to: 'users#show', as: 'user_show'
  get 'about', to: 'pages#about'
  get 'agent', to: 'users#agent'
  get 'withdrawals', to: 'withdrawals#index'
  get 'contact', to: 'pages#contact'
  get 'terms', to: 'pages#terms'
  get 'faq', to: 'pages#faq'
  get 'dashboards', to: 'dashboard#index'
  resources :blogs do
    member do
      get :toggle_status
    end
  end
   mount ActionCable.server => '/cable'

root  to: 'pages#home' , as: 'home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/filter.rb
class Filter < ApplicationRecord
	def lists

 	@lists ||= find_lists
   
  end		

 private

 def find_lists

 	lists = Listing.order(:id)
 	lists = lists.where(location:area) if area.present?
 	lists = lists.where(status:status) if status.present?
 	lists = lists.where(bed:bed) if bed.present?
 	lists = lists.where(bath:bath) if bath.present?
 	lists = lists.where("price <= ?", min_price) if min_price.present?
    lists = lists.where("price <= ?", max_price) if max_price.present?
    lists

 

 

 
 end
end

app/models/investment.rb
class Investment < ApplicationRecord
belongs_to :user
has_many :withdrawals, dependent: :destroy
has_many :comments, dependent: :destroy
attribute :last_wd, :date, default: -> { Date.today }
attribute :next_w_date, :date, default: -> { Date.today + 20 }
before_save :default_values,:returns
validates_presence_of :capital, message: 'Capital cannot be blank' 
validates_presence_of :package, message: 'Package cannot be blank' 
 
def default_values
    self.daily ||= '0'  
  end

def returns

	if self.package == 'Local'

    period = 90
    rate = 0.02
    
  self.i_return = self.capital * rate * period 
  self.w_date =  Date.today + period 
   self.next_w_date = Date.today + 20

  else if self.package == 'Local Extra'

    period = 50
    rate = 0.027

    self.i_return = self.capital * rate * period 
      
    self.w_date =  Date.today + period 
    self.next_w_date = Date.today + 40

  else if self.package == 'International'

    period = 90
    rate = 0.02

    self.i_return = self.capital * rate * period 
    self.w_date =  Date.today + period 
    self.next_w_date = Date.today + 40 
    end
    end
  	end
 

  	end

   



end

app/models/topic.rb
class Topic < ApplicationRecord
	validates_presence_of:title
	has_many :blogs,dependent: :destroy
def self.with_blogs
    includes(:blogs).where.not(blogs: { id: nil })
  end
end

app/models/user.rb
class User < ApplicationRecord

  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
 # petergate(roles: [:admin, :editor], multiple: false)   
   petergate(roles: [:site_admin], multiple: false)                                          ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

 
  # User Avatar Validation validates_integrity_of :avatar validates_processing_of :avatar



  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 validates_presence_of :name, message: 'Fullname cannot be blank' 

 validates_presence_of :email, message: 'Email cannot be blank' 

 validates_presence_of :phone, message: 'Phone Number  cannot be blank' 

 
 
 validates :password,confirmation: true, :format => {:with => /\A(?=.*[a-zA-Z])(?=.*[0-9]).{8,}\z/, message: "must be at least 6 characters and include one number and one letter."}
 
 
 has_many :withdrawals, dependent: :destroy

 has_many :investments, dependent: :destroy

 before_save:set_account


  def set_account
    account = "#{accountname} #{accountnumber}#{bankname}"
  end





end

app/models/withdrawal.rb
class Withdrawal < ApplicationRecord
  belongs_to :user
  belongs_to :investment
  before_save :breakdown
  after_save :update_event_status
  require 'date'

 def update_event_status
    investment.update_attributes(last_wd:Date.today)
  end 
def breakdown
    now = Date.today
    before = self.last_with
    days = (now - before).to_i
	period = 90
    rate = 0.02
    
    self.Amount = self.capital * days * rate
     

 end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_helper 
  name = current_user.name
      
   
  end

  def source_helper(layout_name)
    if session[:source]
      greeting = "Thanks for visiting me from #{session[:source]} and you are on the #{layout_name} layout"
      content_tag(:p, greeting, class: "source-greeting")
    end
  end

  def copyright_generator
    DevcampViewTool::Renderer.copyright 'Jordan Hudgens', 'All rights reserved'
  end



  def nav_items
    [
      {
        url: home_path,
        title: 'Home'
      },
      {
        url: about_path,
        title: 'About Us'
      },
      {
        url: faq_path,
        title: 'FAQ'
      },
      
      {
        url: terms_path,
        title: 'Terms and Condition'
      },
      {
        url: contact_path,
        title: 'Contact Us'
      },
      
    ]
  end

  def nav_helper style, tag_type
    nav_links = ''

    nav_items.each do |item|
      nav_links << "<li><a href='#{item[:url]}' class='#{style} #{active? item[:url]}'>#{item[:title]}</a></li>"
    end

    nav_links.html_safe
  end

  def active? path
    "active" if current_page? path
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper
  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 60
  end

  
  def blog_status_color blog
    'color: red;' if blog.draft?
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/helpers/investment_helper.rb
module InvestmentHelper
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
	def twitter_parser tweet
    regex = %r{
      \b
      (
        (?: [a-z][\w-]+:
         (?: /{1,3} | [a-z0-9%] ) |
          www\d{0,3}[.] |
          [a-z0-9.\-]+[.][a-z]{2,4}/
        )
        (?:
         [^\s()<>]+ | \(([^\s()<>]+|(\([^\s()<>]+\)))*\)
        )+
        (?:
          \(([^\s()<>]+|(\([^\s()<>]+\)))*\) |
          [^\s`!()\[\]{};:'".,<>?«»“”‘’]
        )
      )
    }ix
     tweet.gsub(regex) do |url|
      "<a href='#{url}' target='_blank'>#{url}</a>"
    end.html_safe
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end

  def portfolio_img img, type
 
    if img.model.main_image? || img.model.thumb_image?
     
      
    img.url

    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/withdrawals_helper.rb
module WithdrawalsHelper
end

app/views/dashboards/_form.html.erb
<%= form_with(model: dashboard, local: true) do |form| %>
  <% if dashboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dashboard.errors.count, "error") %> prohibited this dashboard from being saved:</h2>

      <ul>
      <% dashboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>



<% unless current_user.is_a? GuestUser %>
  <%= form_for @comment, url: '#' do |f| %>
    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control' %>
    </div>
     <%= f.submit 'Post Comment', class: 'btn btn-primary' %>
  <% end %>
<% end %> 

app/views/dashboards/edit.html.erb
<h1>Editing Dashboard</h1>

<%= render 'form', dashboard: @dashboard %>

<%= link_to 'Show', @dashboard %> |
<%= link_to 'Back', dashboards_path %>

app/views/dashboards/new.html.erb
<h1>New Dashboard</h1>

<%= render 'form', dashboard: @dashboard %>

<%= link_to 'Back', dashboards_path %>

app/views/dashboards/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_dashboard_path(@dashboard) %> |
<%= link_to 'Back', dashboards_path %>

app/views/filters/_aside.html.erb
 <aside id="edit-search">
                            <header><h3>Search Properties</h3></header>


<%=  form_for Filter.new, :html => {:class => 'form-search', :id => 'form-sidebar'}  do |form| %>
   <h2>Search Your Property</h2>
  <div class="form-group">
    
   <%= form.select(:area, options_for_select([['Select Location',''],['Mainland-Lagos','Mainland-Lagos'],['Island-Lagos','Island-Lagos']])) %>
  </div>

  <div class="form-group">
  
     <%= form.select(:status, options_for_select([['Select status',''],['Sale','Sale'],['Rent','Rent']])) %>
  </div>

  <div class="form-group">
  
     <%= form.select(:bed, options_for_select([['Select Bedroom',''],['1','1'],['2','2'],['3','3'],['4','4'],['5','5']] )) %>
  </div>


  <div class="form-group" >
    
     <%= form.select(:bath, options_for_select([['Select Bathroom',''],['1','1'],['2','2'],['3','3'],['4','4'],['5','5']] )) %>
  </div> 


 
  <div class="actions" style="padding-bottom: 20px">
    <%= form.submit 'Search Now',  :class => 'btn btn-default' %>
  </div>
<% end %>
                           
                        </aside><!-- /#edit-search -->

app/views/filters/_form.html.erb
  <div class="search-box-wrapper">
        <div class="search-box-inner">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-md-offset-9 col-sm-4 col-sm-offset-8">
                        <div class="search-box map">
                           
                               

<%=  form_for Filter.new, :html => {:class => 'form-map form-search', :id => 'form-map form-search'}  do |form| %>
   <h2>Search Your Property</h2>
  <div class="field">
    <%= form.label :area %>
   <%= form.select(:area, options_for_select([['Select Location',''],['Mainland-Lagos','Mainland-Lagos'],['Island-Lagos','Island-Lagos']])) %>
  </div>

  <div class="field">
    <%= form.label :status %>
     <%= form.select(:status, options_for_select([['Select status',''],['Sale','Sale'],['Rent','Rent']])) %>
  </div>

  <div class="field">
    <%= form.label :Bedroom %>
     <%= form.select(:bed, options_for_select([['Select Bedroom',''],['1','1'],['2','2'],['3','3'],['4','4'],['5','5']] )) %>
  </div>


  <div class="field" style="padding-bottom: 20px">
    <%= form.label :Bathroom %>
     <%= form.select(:bath, options_for_select([['Select Bathroom',''],['1','1'],['2','2'],['3','3'],['4','4'],['5','5']] )) %>
  </div> 


 
  <div class="actions" style="padding-bottom: 20px">
    <%= form.submit 'Search Now',  :class => 'btn btn-default' %>
  </div>
<% end %>

   </div>
                    </div>
                </div>
            </div>
        </div>
    </div>  

app/views/filters/edit.html.erb
<h1>Editing Filter</h1>

<%= render 'form', filter: @filter %>

<%= link_to 'Show', @filter %> |
<%= link_to 'Back', filters_path %>

app/views/filters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Filters</h1>

<table>
  <thead>
    <tr>
      <th>Area</th>
      <th>Status</th>
      <th>Min price</th>
      <th>Max price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @filters.each do |filter| %>
      <tr>
        <td><%= filter.area %></td>
        <td><%= filter.status %></td>
        <td><%= filter.min_price %></td>
        <td><%= filter.max_price %></td>
        <td><%= link_to 'Show', filter %></td>
        <td><%= link_to 'Edit', edit_filter_path(filter) %></td>
        <td><%= link_to 'Destroy', filter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Filter', new_filter_path %>

app/views/filters/new.html.erb
<h1>New Filter</h1>

<%= render 'form', filter: @filter %>

<%= link_to 'Back', filters_path %>